real base,altura,area
caracter siga
inicio
    siga <- 'S'
    mientras (siga = 'S') o (siga = 'S') haga
        escriba "Base ?"
        lea base
        escriba "Altura ?"
        lea altura
        area <- base * altura /2
        escriba "El area es ", area
        llamar nueva_linea
        escriba "Desea continuar? (S/N)"
        lea siga
        llamar limpiar_pantalla
     fin mientras
fin